apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aegis-platform
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cms553
  annotations:
    backstage.io/email: cms553@cornell.edu
spec:
  profile:
    displayName: cms553
    email: cms553@cornell.edu
  memberOf: []
