apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis-ui.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegis-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.env.BACKEND_SECRET }}
  backend-secret: {{ .Values.env.BACKEND_SECRET | quote }}
  {{- end }}
  {{- if .Values.keycloak.clientSecret }}
  keycloak-client-secret: {{ .Values.keycloak.clientSecret | quote }}
  {{- end }}
  {{- if and .Values.postgres.password (not .Values.postgres.existingSecret) }}
  postgres-password: {{ .Values.postgres.password | quote }}
  {{- end }}
